name: Deploy to AWS CloudFront
run-name: Deploy to AWS CloudFront 🚀

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.8

      - name: AWS CLI installation
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: PWD execute
        run: pwd
      - name: Debug
        run: |
          cd /home/runner/work/portforio-frontend/portforio-frontend/src/components/organisms
          pwd

      - name: Install dependencies
        run: yarn install
      - name: Build and deploy
        run: |
          yarn build
          aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET }} --recursive
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUD_FRONT_DISTRIBUTION_ID }} --paths '/*'
